### ISSUE TITLE
Villager not stacking discounts on cure

### ISSUE THREAD

**Issue by Lcreager** [MarioFinale/VillagerSaver#18]
Spigot 1.18.2
Plugin Version 1.2.5

When healing a villager, the major and minor positives are always set to 20 and 25 respectively instead of incrementing.

Disabling the plugin and setting the difficulty to Hard, the values are incrementing correctly after each cure.

I found the values using the following in game command: 
```
/data get entity @e[type=minecraft:villager, limit=1, sort=nearest]
```

**Comment by MarioFinale** [comment]
Thank for the report, that's weird, the plugin doesn't handle the villager curing mechanic. More specifically: It checks when a villager gets hits and if it should die, then checks if the damager is a zombie and then transforms it keeping its trade data.

I'll give the plugin a deeper look but if you are using PaperMC you may want to check if the issue is caused by the setting _fix-curing-zombie-villager-discount-exploit: true_ on paper.yml in fact,[ I found the exact PaperMC Patch that does that](https://ci.denwav.dev/diffView.html?id=7399&vcsFileName=patches%2Fserver%2F0566-Fix-curing-zombie-villager-discount-exploit.patch&personal=false), on the last two lines you can see how they manually set the reputation to 20 and 25 respectively.

**Comment by Lcreager** [comment]
I am using Spigot to run the server.  I kind of poked around but did not see anything which seemed like it would make a difference in the config.

**Comment by MarioFinale** [comment]
Hi, you might want to try the latest 1.3.2 version of the plugin, it fundamentally changes the way villagers are zombified, it should fix your issue.
